### ISSUE TITLE
[16.0] Build broken - facturx

### ISSUE THREAD

**Issue by simahawk** [OCA/edi#1086]
```
 2024-12-04 05:51:24,172 3177 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 489, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/odoo/modules/loading.py", line 373, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo/modules/loading.py", line 283, in load_module_graph
    suite = loader.make_suite([module_name], 'at_install')
  File "/opt/odoo/odoo/tests/loader.py", line 76, in make_suite
    return OdooSuite(sorted(tests, key=lambda t: t.test_sequence))
  File "/opt/odoo/odoo/tests/loader.py", line 72, in <genexpr>
    for m in get_test_modules(module_name)
  File "/opt/odoo/odoo/tests/loader.py", line 19, in get_test_modules
    results = _get_tests_modules(importlib.util.find_spec(f'odoo.addons.{module}'))
  File "/opt/odoo/odoo/tests/loader.py", line 30, in _get_tests_modules
    tests_mod = importlib.import_module(spec.name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/__w/edi/edi/account_invoice_facturx/tests/__init__.py", line 1, in <module>
    from . import test_facturx_invoice
  File "/__w/edi/edi/account_invoice_facturx/tests/test_facturx_invoice.py", line 7, in <module>
    from facturx import get_facturx_level
  File "/opt/odoo-venv/lib/python3.10/site-packages/facturx/__init__.py", line 1, in <module>
    from .facturx import generate_from_file, \
  File "/opt/odoo-venv/lib/python3.10/site-packages/facturx/facturx.py", line 34, in <module>
    from pypdf import PdfWriter, PdfReader
ModuleNotFoundError: No module named 'pypdf'
```
Similarly to #1084 the latest `factur-x` version breaks the build but in a different way.

**Comment by simahawk** [comment]
This is the change https://github.com/akretion/factur-x/commit/0d354d4cf4424a2c51ceb05c3d01a7d849518305

**Comment by simahawk** [comment]
@alexis-via ping :)
