### ISSUE TITLE
[12.0] sale_order_ubl TypeError: a bytes-like object is required, not 'tuple'

### ISSUE THREAD

**Issue by jchanme** [OCA/edi#190]
When I tried to print a quotation, either the button or action menu, it will prompt an error:
`Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-12/addons/web/controllers/main.py", line 1671, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/opt/odoo/odoo-12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons-test/report_xlsx/controllers/main.py", line 59, in report_routes
    reportname, docids, converter, **data
  File "/opt/odoo/odoo-12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-12/addons/web/controllers/main.py", line 1612, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/addons-test/sale_order_ubl/models/report.py", line 22, in render_qweb_pdf
    pdf_content = order.embed_ubl_xml_in_pdf(pdf_content=pdf_content)
  File "/opt/odoo/addons-test/sale_order_ubl/models/sale.py", line 193, in embed_ubl_xml_in_pdf
    pdf_content=pdf_content, pdf_file=pdf_file)
  File "/opt/odoo/addons-test/base_ubl/models/ubl.py", line 529, in embed_xml_in_pdf
    original_pdf_file = BytesIO(pdf_content)
TypeError: a bytes-like object is required, not 'tuple'`

I went through the server debug log, there is nothing like this, the last lines of logs is like this:
`2020-04-17 04:38:29,773 21872 DEBUG test odoo.addons.base_ubl.models.ubl: Starting to embed UBL-Quotation-2.1.xml in PDF file
2020-04-17 04:38:29,779 21872 INFO test werkzeug: 10.10.10.50 - - [17/Apr/2020 04:38:29] "POST /report/download HTTP/1.0" 200 - 453 0.815 8.514`

I can't figure out why this is happening, can anyone help?

**Comment by cvinh** [comment]
I have the same error, I think it's related to wkhtmltopdf ? What is your version ?

**Comment by cvinh** [comment]
I noticed that @alexis-via improved the reporting engine here https://github.com/OCA/edi/commit/919275edef5f5e206954cc6159217dc4e4cdfd67#diff-1a1059837c383f5c8f3831ffd2260b9a
but the sale_order_ubl module hasn't been updated to that improvement

**Comment by cvinh** [comment]
I did a PR here : https://github.com/OCA/edi/pull/195

**Comment by jchanme** [comment]
@cvinh @alexis-via Thank you for the PR and the merge! Great work.
