### ISSUE TITLE
Failure to install ZuGFERD modules

### ISSUE THREAD

**Issue by mmatousek** [OCA/edi#20]
Hi
I am trying to install the ZuGFERD modules for ODOO 8.0 on my test-setup and I am running into a bit of a problem:
` Traceback (most recent call last):
  File "/home/markus/odoo-dev/odoo/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/markus/odoo-dev/odoo/openerp/http.py", line 584, in dispatch
    result = self._call_function(**self.params)
  File "/home/markus/odoo-dev/odoo/openerp/http.py", line 318, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/markus/odoo-dev/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/markus/odoo-dev/odoo/openerp/http.py", line 315, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/markus/odoo-dev/odoo/openerp/http.py", line 822, in __call__
    return self.method(*args, **kw)
  File "/home/markus/odoo-dev/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/home/markus/odoo-dev/odoo/addons/web/controllers/main.py", line 968, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/markus/odoo-dev/odoo/addons/web/controllers/main.py", line 956, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/markus/odoo-dev/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/markus/odoo-dev/odoo/openerp/addons/base/module/wizard/base_module_upgrade.py", line 105, in upgrade_module
    openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/markus/odoo-dev/odoo/openerp/modules/registry.py", line 371, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/markus/odoo-dev/odoo/openerp/modules/loading.py", line 354, in load_modules
    loaded_modules, update_module)
  File "/home/markus/odoo-dev/odoo/openerp/modules/loading.py", line 254, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/markus/odoo-dev/odoo/openerp/modules/loading.py", line 175, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/markus/odoo-dev/odoo/openerp/modules/loading.py", line 117, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/markus/odoo-dev/odoo/openerp/tools/convert.py", line 862, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/markus/odoo-dev/odoo/openerp/tools/convert.py", line 949, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/markus/odoo-dev/odoo/openerp/tools/convert.py", line 812, in parse
    self.parse(rec, mode)
  File "/home/markus/odoo-dev/odoo/openerp/tools/convert.py", line 815, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/markus/odoo-dev/odoo/openerp/tools/convert.py", line 516, in _tag_menuitem
    menu_parent_id = self.id_get(cr, rec.get('parent',''))
  File "/home/markus/odoo-dev/odoo/openerp/tools/convert.py", line 793, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/home/markus/odoo-dev/odoo/openerp/tools/convert.py", line 804, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/home/markus/odoo-dev/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/markus/odoo-dev/odoo/openerp/addons/base/ir/ir_model.py", line 904, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/home/markus/odoo-dev/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/home/markus/odoo-dev/odoo/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/markus/odoo-dev/odoo/openerp/addons/base/ir/ir_model.py", line 894, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: account.menu_configuration_misc" while parsing /home/markus/odoo-dev/bank-payment/account_banking_payment_export/views/payment_mode_type.xml:63, near
<menuitem id="menu_payment_mode_type" action="action_payment_mode_type" parent="account.menu_configuration_misc"/> `

Can somebody tell me, what I am doing wrong? I have met all dependencies and I am using the right branches.

**Comment by alexis-via** [comment]
The XMLID account.menu_configuration_misc is defined in the official "account" module here:
https://github.com/odoo/odoo/blob/8.0/addons/account/account_menuitem.xml#L32
So the problem is on your side. You probably deleted the menu "Accounting > Configuration > Misc"...

Try to restart odoo with these additional options on the command line:  "-u account -d <your_database>"
