### ISSUE TITLE
Build red on 14.0 and 15.0 branch

### ISSUE THREAD

**Issue by simahawk** [OCA/edi#818]
```
 2023-09-22 11:11:08,170 1786 ERROR odoo odoo.addons.edi_oca.tests.test_security: FAIL: TestEDIExchangeRecordSecurity.test_rule_no_create
odoo.exceptions.AccessError: Due to security restrictions, you are not allowed to modify 'Model used only for test' (edi.exchange.consumer.test) records.

Contact your administrator to request access if necessary.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/misc.py", line 885, in deco
    return func(*args, **kwargs)
  File "/__w/edi/edi/edi_oca/tests/test_security.py", line 90, in test_rule_no_create
    self.create_record(self.user)
AssertionError: "Exchange Record rule demo" does not match "Due to security restrictions, you are not allowed to modify 'Model used only for test' (edi.exchange.consumer.test) records.

```
The same test was passing before. Something has probably changed somewhere else.

**Comment by simahawk** [comment]
I have no time this week. @etobella if you have time to check, be my guest :wink:
